name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl ""
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Git Identity
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Website Branch
        run: |
          git checkout --orphan website
          git reset --hard
          git commit --allow-empty -m "Initial commit on website branch"
          git push origin website

      - name: Checkout Website Branch
        uses: actions/checkout@v4
        with:
          ref: website

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: _site
          path: .

      - name: Commit and Push to Website Branch
        run: |
          git add .
          git commit -m "Deploy Jekyll site"
          git push origin HEAD:website
        if: github.ref == 'refs/heads/main'